services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      TZ: ${TZ:-Asia/Jakarta}
      GENERIC_TIMEZONE: ${TZ:-Asia/Jakarta}
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: ${N8N_DB_NAME:-n8n}
      DB_POSTGRESDB_HOST: ${N8N_DB_HOST:-postgres}
      DB_POSTGRESDB_PORT: ${N8N_DB_PORT:-5432}
      DB_POSTGRESDB_USER: ${N8N_DB_USER:-root}
      DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_PASSWORD: ${N8N_DB_PASSWORD:-password}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - homelab
    deploy:
      resources:
        limits:
          cpus: "${N8N_CPU_LIMIT:-1}"
          memory: ${N8N_MEMORY_LIMIT:-1G}

networks:
  homelab:
    external: true

volumes:
  n8n_data:
