services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open_webui_data:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT:-3092}:8080
    environment:
      - "OLLAMA_BASE_URL=${OPEN_WEBUI_OLLAMA_BASE_URL:-http://ollama:11434}"
      - "WEBUI_SECRET_KEY=${OPEN_WEBUI_SECRET_KEY:-01KFMDGRBV05GP11TJKCTK7DHG}"
    networks:
      - homelab
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "${OPEN_WEBUI_CPU_LIMIT:-1}"
          memory: ${OPEN_WEBUI_MEMORY_LIMIT:-2G}

networks:
  homelab:
    external: true

volumes:
  open_webui_data:
